version: "3.7"

volumes:
  pgdata:

services:
  app:
    container_name: app
    env_file:
      - .env
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000
    ports:
      - '5000:5000'
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    #environment:
    #  POSTGRES_USER: user
    #  POSTGRES_PASSWORD: password

    env_file:
      - .env

    ports:
      - '5433:5433'

    restart: on-failure


